name: Jalankan Tes Web dan API

# Pemicu: Jalankan saat ada push ke main atau dipicu manual
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 1: Instal Allure Commandline (dibutuhkan untuk membuat laporan)
      - name: Install Allure Commandline
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g allure-commandline --unsafe-perm

      # Langkah 2: Siapkan Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Langkah 3: Instal Chrome/WebDriver & Dependencies (HEADLESS SETUP)
      # Menggunakan actions-setup-chrome untuk menginstal Chrome dan ChromeDriver
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@latest

      # Langkah 4: Install Dependencies Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Langkah 5: Jalankan Tes Selenium
      - name: Run Web Tests with Pytest & Allure
        # --headless flag tidak diperlukan karena sudah ditangani oleh setup-chrome
        run: pytest WEB_PROJECTS/SauceDemo/ --alluredir=allure-results
        
      # Langkah 6: Simpan Data Allure
      - name: Upload Allure Report Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 5
          
  # Job terpisah untuk tes API (opsional, bisa digabung)
  test-api:
    runs-on: ubuntu-latest
    needs: test-web # Menunggu tes web selesai
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run API tests with pytest
        run: pytest API/

  publish-allure-report:
    runs-on: ubuntu-latest
    needs: test-web # Pastikan ini menunggu job tes Anda selesai
    if: always() 

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      # Langkah 1: Download hasil tes mentah (allure-results)
      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      # Langkah 2: Instal Allure CTL (Commandline Tool) menggunakan action resmi
      - name: Setup Allure
        uses: allure-framework/setup-allurectl@v1

      # Langkah 3: Generate laporan Allure menggunakan perintah yang baru diinstal
      - name: Generate Allure Report
        run: allurectl report generate --report-dir allure-report ./allure-results

      # Langkah 4: Publikasikan folder laporan ke branch gh-pages
      - name: Deploy Allure Report to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Pastikan publish_dir mengarah ke folder output dari langkah sebelumnya
          publish_dir: ./allure-report