name: Jalankan Tes API Otomatis

# Pemicu: Jalankan workflow ini setiap kali ada 'push' ke branch 'main'
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Memungkinkan kita menjalankan manual

jobs:
  test-api:
    # Mesin virtual yang akan digunakan: Ubuntu versi terbaru
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: "Checkout" atau unduh kode dari repositori
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Siapkan lingkungan Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Langkah 3: Install semua library yang dibutuhkan dari requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Langkah 4: Jalankan hanya tes API
      - name: Run API tests with pytest
        run: pytest API/